// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGgS7NoRLgrjj7e0ttA7Dy68Zvr_NQNeU',
    appId: '1:639260794813:web:0ee5609e939341f2e77cd4',
    messagingSenderId: '639260794813',
    projectId: 'techmageddon-1st',
    authDomain: 'techmageddon-1st.firebaseapp.com',
    storageBucket: 'techmageddon-1st.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFLhuzV4eYcxo2cCPZDffhLWNlRw17Do',
    appId: '1:639260794813:android:2283a87019a810eae77cd4',
    messagingSenderId: '639260794813',
    projectId: 'techmageddon-1st',
    storageBucket: 'techmageddon-1st.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm4URVGePEXqLJbqLd814lJsyi5O8Lz6o',
    appId: '1:639260794813:ios:fdd8432f7ae18e18e77cd4',
    messagingSenderId: '639260794813',
    projectId: 'techmageddon-1st',
    storageBucket: 'techmageddon-1st.firebasestorage.app',
    iosBundleId: 'techmageddon1stv2.com.example.techmageddon1stV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm4URVGePEXqLJbqLd814lJsyi5O8Lz6o',
    appId: '1:639260794813:ios:fdd8432f7ae18e18e77cd4',
    messagingSenderId: '639260794813',
    projectId: 'techmageddon-1st',
    storageBucket: 'techmageddon-1st.firebasestorage.app',
    iosBundleId: 'techmageddon1stv2.com.example.techmageddon1stV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGgS7NoRLgrjj7e0ttA7Dy68Zvr_NQNeU',
    appId: '1:639260794813:web:64d882e1b85ffaf4e77cd4',
    messagingSenderId: '639260794813',
    projectId: 'techmageddon-1st',
    authDomain: 'techmageddon-1st.firebaseapp.com',
    storageBucket: 'techmageddon-1st.firebasestorage.app',
  );
}
